### ISSUE TITLE
Replace "ifconfig" by "ip"

### ISSUE THREAD

**Issue by J0hnMatrix** [branning/hs100#2]
Hello and many thanks for your scripts!
As the "ifconfig" command has been deprecated, have you the possibility to modify the "myip.sh" script to use the command "ip" instead?

Many thanks in advance!

**Comment by branning** [comment]
Cool, thanks. I have been off Ubuntu for a while, and didn't notice the change. Lots of stuff was deprecated.

This should be fixed in d079f4bef
