### ISSUE TITLE
Error running it

### ISSUE THREAD

**Issue by adminclubopel** [branning/hs100#5]
hi, sorry i get an error trying to run it, where is should put the file on my linux enviroment? thanks

**Comment by adminclubopel** [comment]
i solved it with chmod +x hs100.sh

**Comment by branning** [comment]
Okay glad that works

**Comment by adminclubopel** [comment]
@branning i have 3 h100 on my network and the script add whole plugs ips on my hosts, can ir run the command on or off for a specific h100 plug?

**Comment by adminclubopel** [comment]
well i auto-respond my doubts ... 

Usage: ./hs100.sh [-i IP] [-p PORT] COMMAND

thanks and sorry

**Comment by adminclubopel** [comment]
many thanks for this great script :-)
